name: ðŸš€ Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to bahamm.ir
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸ“¦ Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/bahamm-git
            git pull origin main
            pm2 restart backend
            pm2 restart frontend
            echo "âœ… Deploy completed successfully!"
