name: âš¡ Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Reload Server
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: ðŸ”„ Reload Hotload Services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 20s
          script: |
            cd ~/bahamm-git
            git pull -q
            pm2 reload backend
            pm2 reload frontend
